
SPACESHIP_SEPARATOR_SHOW="${SPACESHIP_SEPARATOR_SHOW=true}"
SPACESHIP_SEPARATOR_COLOR="${SPACESHIP_SEPARATOR_COLOR="white"}"
SPACESHIP_SEPARATOR_SYMBOL="${SPACESHIP_SEPARATOR_SYMBOL="\u2500"}"

spaceship_separator() {
  LINE=$(printf "${SPACESHIP_SEPARATOR_SYMBOL}%.0s" {1..$COLUMNS})

  spaceship::section \
    "$SPACESHIP_SEPARATOR_COLOR" \
    "\n${LINE}"
}
